### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by xxkainexx** [kreezxil/wpc#2]
Getting a client crash that has to do with some sound event from metamorph from the looks of it.

I was morphed into an ancient golem from Embers and was just digging sand in the water, and the client crashed and am unable to join back in without crashing.

[crash-2019-12-03_01.32.55-client.txt](https://github.com/mchorse/metamorph/files/3915206/crash-2019-12-03_01.32.55-client.txt)

https://github.com/mchorse/metamorph/issues/192

**Comment by kreezxil** [comment]
btw, please learn to use https://pastebin.com most devs will pitch a fit  having to download your log then opening  a shell folder then double clicking the download.

when it is so much easier to click a link.

here is how to do it, more work for you but less work for everyone in perpetuity:
1. open the text file
1. copy everything (ctrl+a) then (ctrl+c)
1. goto pasting service such as https://pastebin.com or https://paste.ubuntu.com
1. in the giant white box click in it
1. paste (ctrl+v)
1. find the submit button and hit it
1. the page will refresh
1. the address at the top in the url bar, copy it, it'll have rando characters in it
1. paste that back to the report
1. profit

### * On MAC use cmd instead of ctrl

**Comment by kreezxil** [comment]
this guy is active so unless you can't connect to the server we'll wait on his update.

**Comment by kreezxil** [comment]
you can't get back in I see, so we're gonna switch this for the other one.

```
[1:40 AM] Kaine: welp already broke it
[8:00 AM] Kreezxil: @Kaine can you get back in?
[9:48 AM] Kaine: i am unable to get back in
[10:16 AM] Kreezxil: well there goes the morph mod, I'll switch it for the other morph mod
```
