### ISSUE TITLE
Mod Suggestion OpenComputers

### ISSUE THREAD

**Issue by xxkainexx** [kreezxil/wpc#23]
Suggesting because always fun to play with computers.
https://www.curseforge.com/minecraft/mc-mods/opencomputers/files/2828357

**Comment by kreezxil** [comment]
the pack has computer craft which everyone complains about because of LUA.
Computercraft uses a simple version of lua designed especially for
minecraft.

OpenComputers uses legit standard lua. You'd think that would make it
easier but it actually makes it harder. ... because now you need a formal
education in lua.

Adding this mod technically adds bloat. even less people will use it over
computercraft.

top reasons that is so:
* opencomputers doesn't have a forum where you can get opencomputers
programs
* when you seek help on opencomputers forums you're told to RTFM (READ THE
FUCKING MANUAL) and go learn LUA
* computercraft does  have a forum loaded with programs you can use
* when you seek help on computercraft forums nobody tells you to RTFM or to
go learn LUA, some even offer write it for you
* I have a few computercraft programs I wrote myself and saved in one of my
githubs
* you can search github and pastebin for lua and 99% of what comes up is a
computercraft program, not opencomputers, and not a WOW ACE plugin.

**Comment by kreezxil** [comment]
I will add this to preview e, but I want to see you do something with it before I publish this pack to the LIVES.
